<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Center for Plant Conservation, cpc, flora of pakistan, flora, botany, herbarium, botanic garden" />
<meta content="Welcome to the Center for Plant Conservation, University of Karachi"  name=description>

<title>Center for Plant Conservation</title>
<!-- // Stylesheets // -->
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<!-- // JavaScript // -->
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/cufon-yui.js"></script>
<script type="text/javascript" src="/js/arial.js"></script>
<script type="text/javascript" src="/js/chilli.js"></script>
<script type="text/javascript" src="/js/cycle.js"></script>
<script type="text/javascript" src="/js/functions.js"></script>
<script type="text/javascript" src="/js/fancybox.js"></script>
</head>
<body>
<?php
   $path = $_SERVER['DOCUMENT_ROOT'];
   $path .= "/top.htm";
   include_once($path);
?>
<div id="outer_content">
<div id="content">
<div id="breadcrumb">
<ul>
<li><a href="/">Home</a></li>
<li><a href="/research_institutes/index.php">Institutes</a></li>
<li><a href="/research_institutes/cpc/index.php">Center for Plant Conservation</a></li>
<li><a href="#" class="active">Flora of Pakistan</a></li>
</ul>
</div>

<div id="banner_inner">
<div id="banner_inner_wrapp">
<img src="/images/banner-blog.jpg" alt="" />
<h1>Center for Plant Conservation</h1>
</div>
</div>
<div id="courses_sec">
<div class="heading_content">
<h2>Flora of Pakistan</h2>
</div>
<div class="course_content">
  <div class="left_course">
  <h2>&nbsp;</h2>
<div class="course_menu">
<ul>
<li><a href="index.php">Introduction</a></li>
<li><a href="faculty.php">Faculty</a></li>
<li><a href="#">Flora of Pakistan</a></li>
<li><a href="docs/pollen.pdf" target="_blank">Book Publications</a></li>
<li><a href="herbarium.php">Herbarium</a></li>
<li><a href="botanic.php">Botanic Garden</a></li>
<li><a href="program.php">Programs</a></li>
<li><a href="res.php">Research</a></li>
<li><a href="resp.php">Research Productivity</a></li>
<li><a href="event.php">Events</a></li>
<li><a href="contact.php">Contact</a></li>
</ul>
</div>
</div>
<div class="right_course">
 <p>&nbsp;</p> 
<!--  <table width="100%" border="0" align="right">
    <tr>
      <td width="80%"><div align="right"></div></td>
      <td><div align="right"><a href="ohcpc.jpg" target="_blank"><img src="/research_institutes/cpc/images/cpcevent.png" width="120" height="30" alt=""/></a></div></td>
    </tr>
    </table>    -->
  <p><strong><u>A Historic achievement</u></strong><br />
    <strong>Flora  of Pakistan</strong></p>
   <p align="justify">Flora  of Pakistan is the complete modern account of the plants of South Asia. It is  comprehensive and most reliable documented series covering diversified flora  spread in various regions of Southwest Asia in general and Pakistan in  particular.</p>
<p align="justify">It  is edited by world renowned scientists Syed Irtifaq Ali, Eugene Nasir &amp;  Muhammad Qaiser. The treatment of some larger families such as Poaceae (T. A.  Cope, Kew), Cyperaceae (I. Kukkonen, Helsinki), Labiatae (Ian Hedge, Edinburgh)  and Rosaceae (Landrein, Borosova, Osbone &amp; Ghazanfar, Kew) has been done by  the world renowned taxonomists. The Flora of Pakistan project was initiated in  1968 and produced 225 treatments covering flowering plants, ranging in size  from a few pages to approximately 500 pages (such as Poaceae) and the last  fascicle Cactaceae 225 was published in February 2021.</p>
 <p align="justify">The  Flora provides detailed description of families and genera and species along  with complete synonymy, and keys to the genera and species, vernacular names,  line drawings of selected species, type information. It also provides baseline  information on the geographical and ecological distribution, phenology, and  ethnobotanical uses of plants. The description of the species is followed by  the examined specimens scattered in local and foreign herbaria such as Kew, BM,  B, M, W, arranged according to a 2° x 2° grid system.</p>
 <p align="justify"><strong>Online  Flora:</strong> The entire Flora is online  (beside the hard copy) with the collaboration of Missouri Botanical Garden,  USA. TROPICOS:</p>
<p align="justify">  <a href="http://www.tropicos.org/%20project/%20Pakistan">http://www.tropicos.org/  project/ Pakistan</a><br /><br />
  <a href="Flora of Pakistan@efloras.org/flora taxon">Flora of  Pakistan@efloras.org/flora taxon</a><br /><br />
    Hard  copies of complete volumes are available at Centre for Plant Conservation, and  Prof. Dr. S. I. Ali Botanic Garden, University of Karachi.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p align="center"><img src="images/fopflyer.jpg" alt="fop" width="665" height="625" /></p> 
<p>&nbsp;</p>
<p>&nbsp;</p>
<table cellspacing="0" cellpadding="0" align="center" border="0">
  <col width="327" />
  <col width="107" />
  <col width="123" />
  <tr>
    <td colspan="3">PRICE OF PUBLISHED FLORA OF PAKISTAN </td>
  </tr>
  <tr>
    <td colspan="3">ALPHABETICAL ORDER</td>
  </tr>
  <tr>
    <td width="338">Name of    Family</td>
    <td width="96">Vol. No.</td>
    <td width="241">Price (Rs.)</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Acanthaceae</td>
    <td>188</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Aceraceae</td>
    <td>92</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Adoxaceae</td>
    <td>151</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Agavaceae</td>
    <td>156</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Aizoaceae</td>
    <td>41</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Alangiaceae</td>
    <td>50</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Alismataceae</td>
    <td>68</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Alliaceae</td>
    <td>83</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Amaranthaceae</td>
    <td>71</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Amaryllidaceae</td>
    <td>134</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Anacardiaceae</td>
    <td>152</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Annonaceae</td>
    <td>167</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Apocynaceae</td>
    <td>148</td>
    <td>1200</td>
  </tr>
  <tr>
    <td>Aquifoliaceae</td>
    <td>124</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Araceae</td>
    <td>120</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Araliaceae</td>
    <td>86</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Araucariaceae(Gymnospermae)</td>
    <td>181</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Aristolochiaceae</td>
    <td>110</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Asclepiadaceae</td>
    <td>150</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Asparagaceae</td>
    <td>217</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Asphodelaceae</td>
    <td>211</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Asteraceae (I)</td>
    <td>207</td>
    <td>6880</td>
  </tr>
  <tr>
    <td>Asteraceae (II)</td>
    <td>210</td>
    <td>8600</td>
  </tr>
  <tr>
    <td>Asteraceae (III)</td>
    <td>218</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Asteraceae (IV)</td>
    <td>222</td>
    <td>14240</td>
  </tr>
  <tr>
    <td>Asteraceae (V)</td>
    <td>223</td>
    <td>14520</td>
  </tr>
  <tr>
    <td>Asteraceae (VI)</td>
    <td>224</td>
    <td>12400</td>
  </tr>
  <tr>
    <td>Averrhoaceae</td>
    <td>11</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Avicenniaceae</td>
    <td>49</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Balanophoraceae</td>
    <td>135</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Balsaminaceae</td>
    <td>133</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Basellaceae</td>
    <td>161</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Betulaceae</td>
    <td>95</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Begoniaceae</td>
    <td>96</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Berberidaceae</td>
    <td>87</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Biebersteiniaceae</td>
    <td>129</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Bignoniaceae</td>
    <td>131</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Bombacaceae</td>
    <td>119</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Boraginaceae</td>
    <td>191</td>
    <td>9000</td>
  </tr>
  <tr>
    <td>Brassicaceae</td>
    <td>55</td>
    <td>12320</td>
  </tr>
  <tr>
    <td>Buddlejaceae</td>
    <td>56</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Burseraceae</td>
    <td>26</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Butomaceae</td>
    <td>69</td>
    <td>1200</td>
  </tr>
  <tr>
    <td>Buxaceae</td>
    <td>65</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Cactaceae</td>
    <td>225</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Caesalpiniaceae</td>
    <td>54</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Callitrichaceae</td>
    <td>201</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Campanulaceae</td>
    <td>155</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Cannabaceae</td>
    <td>44</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Cannaceae</td>
    <td>145</td>
    <td>1200</td>
  </tr>
  <tr>
    <td>Capparidaceae</td>
    <td>34</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Caprifoliaceae</td>
    <td>174</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Caricaceae</td>
    <td>117</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Caryophyllaceae</td>
    <td>175</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Casuarinaceae</td>
    <td>199</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Celastraceae</td>
    <td>109</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Ceratophyllaceae</td>
    <td>70</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Chenopodiaceae</td>
    <td>204</td>
    <td>9585</td>
  </tr>
  <tr>
    <td>Cistaceae</td>
    <td>112</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Colchicaceae</td>
    <td>125</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Combretaceae</td>
    <td>122</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Commelinaceae</td>
    <td>84</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Convallariaceae</td>
    <td>213</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Convolvulaceae</td>
    <td>126</td>
    <td>2500</td>
  </tr>
  <tr>
    <td>Coriariaceae</td>
    <td>43</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Cornaceae</td>
    <td>88</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Corylaceae</td>
    <td>22</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Crassulaceae</td>
    <td>209</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Cucurbitaceae</td>
    <td>154</td>
    <td>2500</td>
  </tr>
  <tr>
    <td>Cupressaceae(Gymnospermae)</td>
    <td>184</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Cuscutaceae</td>
    <td>189</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Cycadaceae (Gymnospermae)</td>
    <td>178</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Cynomoriaceae</td>
    <td>208</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Cyperaceae</td>
    <td>206</td>
    <td>11080</td>
  </tr>
  <tr>
    <td>Datiscaceae</td>
    <td>37</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Dilleniaceae</td>
    <td>42</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Dioscoreaceae</td>
    <td>53</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Dipsacaceae</td>
    <td>94</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Ebenaceae</td>
    <td>116</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Elaeagnaceae</td>
    <td>85</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Elatinaceae</td>
    <td>19</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Ephedraceae(Gymnospermae)</td>
    <td>186</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Ericaceae</td>
    <td>5</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Eriocaulaceae</td>
    <td>142</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Euphorbiaceae</td>
    <td>172</td>
    <td>4000</td>
  </tr>
  <tr>
    <td>Fagaceae</td>
    <td>104</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Flacourtiaceae</td>
    <td>1</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Frankeniaceae</td>
    <td>7</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Fumariaceae</td>
    <td>73</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Gentianaceae</td>
    <td>197</td>
    <td>6880</td>
  </tr>
  <tr>
    <td>Geraniaceae</td>
    <td>149</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Ginkgoaceae(Gymnospermae)</td>
    <td>180</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Goodeniaceae</td>
    <td>30</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Grossulariaceae</td>
    <td>27</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Guttiferae</td>
    <td>32</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Haemodoraceae</td>
    <td>165</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Haloragidaceae</td>
    <td>113</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Hamamelidaceae</td>
    <td>2</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Hemerocallidaceae</td>
    <td>212</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Hippocastanaceae</td>
    <td>82</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Hippuridaceae</td>
    <td>81</td>
    <td>1200</td>
  </tr>
  <tr>
    <td>Hyacinthaceae</td>
    <td>214</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Hydrangeaceae</td>
    <td>16</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Hydrocharitaceae</td>
    <td>169</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Hydrophyllaceae</td>
    <td>127</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Illecebraceae</td>
    <td>47</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Iridaceae</td>
    <td>202</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Iteaceae</td>
    <td>9</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Juglandaceae</td>
    <td>14</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Juncaceae</td>
    <td>138</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Juncaginaceae</td>
    <td>48</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Labiatae</td>
    <td>192</td>
    <td>12400</td>
  </tr>
  <tr>
    <td>Lardizabalaceae</td>
    <td>60</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Lauraceae</td>
    <td>118</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Lecythidaceae</td>
    <td>160</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Lemnaceae</td>
    <td>173</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Lentibulariaceae</td>
    <td>196</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Leonticaceae</td>
    <td>58</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Liliaceae</td>
    <td>215</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Linaceae</td>
    <td>21</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Loranthaceae</td>
    <td>35</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Lythraceae</td>
    <td>78</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Magnoliaceae</td>
    <td>64</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Malpighiaceae </td>
    <td>45</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Malvaceae</td>
    <td>130</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Martyniaceae</td>
    <td>13</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Meliaceae</td>
    <td>17</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Menispermaceae</td>
    <td>74</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Menyanthaceae</td>
    <td>111</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Mimosaceae</td>
    <td>36</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Molluginaceae</td>
    <td>40</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Monotropaceae</td>
    <td>6</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Moraceae</td>
    <td>171</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Morinaceae</td>
    <td>67</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Moringaceae</td>
    <td>38</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Musaceae</td>
    <td>144</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Myrsinaceae</td>
    <td>89</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Myrtaceae</td>
    <td>219</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Najadaceae</td>
    <td>176</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Nelumbonaceae</td>
    <td>194</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Neuradaceae</td>
    <td>198</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Nyctaginaceae</td>
    <td>115</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Nymphaeaceae</td>
    <td>195</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Olacaceae</td>
    <td>136</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Oleaceae</td>
    <td>59</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Onagraceae</td>
    <td>139</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Orchidaceae</td>
    <td>164</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Orobanchaceae</td>
    <td>98</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Oxalidaceae</td>
    <td>4</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Paeoniaceae</td>
    <td>121</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Palmae</td>
    <td>153</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Pandanaceae</td>
    <td>187</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Papaveraceae</td>
    <td>61</td>
    <td>1600</td>
  </tr>
  <tr>
    <td>Papilionaceae</td>
    <td>100</td>
    <td>15560</td>
  </tr>
  <tr>
    <td>Parnassiaceae</td>
    <td>31</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Passifloraceae</td>
    <td>66</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Pedaliaceae</td>
    <td>33</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Philadelphaceae</td>
    <td>15</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Phrymaceae</td>
    <td>46</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Phytolaccaceae</td>
    <td>3</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Pinaceae(Gymnospermae)</td>
    <td>182</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Pittosporaceae</td>
    <td>93</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Plantaginaceae</td>
    <td>62</td>
    <td>1800</td>
  </tr>
  <tr>
    <td>Platanaceae</td>
    <td>23</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Plumbaginaceae</td>
    <td>28</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Poaceae</td>
    <td>143</td>
    <td>27120</td>
  </tr>
  <tr>
    <td>Podophyllaceae</td>
    <td>57</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Polemoniaceae</td>
    <td>8</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Polygalaceae</td>
    <td>52</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Polygonaceae</td>
    <td>205</td>
    <td>6600</td>
  </tr>
  <tr>
    <td>Pontederiaceae</td>
    <td>114</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Portulacaceae</td>
    <td>51</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Potamogetonaceae</td>
    <td>79</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Primulaceae</td>
    <td>157</td>
    <td>4635</td>
  </tr>
  <tr>
    <td>Proteaceae</td>
    <td>72</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Punicaceae</td>
    <td>102</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Pyrolaceae</td>
    <td>128</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Ranunculaceae</td>
    <td>193</td>
    <td>6640</td>
  </tr>
  <tr>
    <td>Resedaceae</td>
    <td>90</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Rhamnaceae</td>
    <td>140</td>
    <td>2500</td>
  </tr>
  <tr>
    <td>Rhizophoraceae</td>
    <td>158</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Rosaceae (I)</td>
    <td>216</td>
    <td>6210</td>
  </tr>
  <tr>
    <td>Rosaceae (II)</td>
    <td>221</td>
    <td>6400</td>
  </tr>
  <tr>
    <td>Rubiaceae</td>
    <td>190</td>
    <td>5800</td>
  </tr>
  <tr>
    <td>Ruppiaceae</td>
    <td>80</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Ruscaceae</td>
    <td>106</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Rutaceae</td>
    <td>132</td>
    <td>2500</td>
  </tr>
  <tr>
    <td>Sabiaceae</td>
    <td>91</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Salicaceae</td>
    <td>203</td>
    <td>6000</td>
  </tr>
  <tr>
    <td>Salvadoraceae</td>
    <td>29</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Sambucaceae</td>
    <td>123</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Santalaceae</td>
    <td>159</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Sapindaceae</td>
    <td>39</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Sapotaceae</td>
    <td>163</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Saxifragaceae</td>
    <td>108</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Scrophulariaceae</td>
    <td>220</td>
    <td>13240</td>
  </tr>
  <tr>
    <td>Simaroubaceae</td>
    <td>162</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Smilacaceae</td>
    <td>107</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Solanaceae</td>
    <td>168</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Sonneratiaceae</td>
    <td>103</td>
    <td>same as 102</td>
  </tr>
  <tr>
    <td>Sparganiaceae</td>
    <td>200</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Sphenocleaceae</td>
    <td>25</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Staphyleaceae</td>
    <td>24</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Sterculiaceae</td>
    <td>99</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Symplocaceae</td>
    <td>63</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Tamaricaceae</td>
    <td>141</td>
    <td>5000</td>
  </tr>
  <tr>
    <td>Taxaceae(Gymnospermae)</td>
    <td>185</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Taxodiaceae(Gymnospermae)</td>
    <td>183</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Thymelaeaceae</td>
    <td>12</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Tiliaceae</td>
    <td>75</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Trapaceae</td>
    <td>97</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Trilliaceae</td>
    <td>105</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Typhaceae</td>
    <td>177</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Ulmaceae</td>
    <td>170</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Umbelliferae</td>
    <td>20</td>
    <td>10000</td>
  </tr>
  <tr>
    <td>Urticaceae</td>
    <td>137</td>
    <td>2500</td>
  </tr>
  <tr>
    <td>Vahliaceae</td>
    <td>10</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Valerianaceae</td>
    <td>101</td>
    <td>1500</td>
  </tr>
  <tr>
    <td>Verbenaceae</td>
    <td>77</td>
    <td>3000</td>
  </tr>
  <tr>
    <td>Violaceae</td>
    <td>166</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Vitaceae</td>
    <td>147</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Zamiaceae(Gymnospermae)</td>
    <td>179</td>
    <td>same as 181</td>
  </tr>
  <tr>
    <td>Zannichelliaceae</td>
    <td>18</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Zingiberaceae</td>
    <td>146</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Zygophyllaceae</td>
    <td>76</td>
    <td>2000</td>
  </tr>
  <tr>
    <td>Total</td>
    <td>&nbsp;</td>
    <td>481110</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Other Books</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="2">Annotated Catalog of the Vascular plants of West Pakistan and    Kashmir</td>
    <td>25000</td>
  </tr>
  <tr>
    <td colspan="2">Chromosome atlas of    Pakistan</td>
    <td>15000</td>
  </tr>
  <tr>
    <td colspan="2">History amd exploration of plants of Pakistan and adjoining    areas</td>
    <td>10000</td>
  </tr>
</table>
</div>
</div>
</div>


<br class="clear" />
</div>
<div id="contentendouter">
    
    
    <div id="contentend">
    
    </div>
  </div>
</div>
<?php
   $path = $_SERVER['DOCUMENT_ROOT'];
   $path .= "/footer.htm";
   include_once($path);
?>
</body>

</html>